name: test-GH
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: build-stage
       run: echo "it's build stage"
  test:
   runs-on: ubuntu-latest
   steps:
     - name: test-stage
       run: echo "test stage it's"
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: deploy-stage
      run: echo "test and deploy the app"
     
   
