name: 2nd day test
on: workflow_dispatch
env:
 APP_VAR: "dev"
jobs:
  test_var:
    env:
     APP_VAR: "test"
    runs-on: ubuntu-latest
    steps:
     - name: running test
       env:
        APP_VAR: "test"
       run: echo "testing vars $APP_VAR"
